{%- if cookiecutter.black|lower == 'y' -%}
[tool.black]
line-length = 120
{% endif -%}

{% if cookiecutter.mypy|lower == 'y' %}
[tool.mypy]
ignore_missing_imports = true
exclude = ["venv/"]
{% endif -%}